default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: mixed-line-ending
    -   id: requirements-txt-fixer
    -   id: check-executables-have-shebangs
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
